# Generated by Django 3.1.1 on 2020-09-18 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diccionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('texto', models.CharField(max_length=150)),
                ('tabla', models.CharField(choices=[('comunicacion', 'Comunicaciones'), ('domicilio', 'Domicilios')], default='comunicacion', max_length=45)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diccionario_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diccionario_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Diccionario',
                'verbose_name_plural': 'Diccionarios',
                'db_table': 'diccionario',
            },
        ),
    ]
