# Generated by Django 3.1.3 on 2021-09-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diccionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diccionario',
            name='codigo',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='diccionario',
            name='tabla',
            field=models.CharField(choices=[('comunicacion', 'Comunicaciones'), ('tipo_domicilio', 'Tipo de Domicilio'), ('tipo_calle', 'Tipo de Calle'), ('tipo_documento', 'Tipo de Documento')], default='comunicacion', max_length=45),
        ),
    ]
